import { Lato } from 'next/font/google'
import './globals.css'


const lato = Lato({ weight: ["100", "300", "400", "700","900"],subsets: ['latin']  })

export const metadata = {
  title: 'QR Menu',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        {children}
        </body>
    </html>
  )
}