import { Lato } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import SearchBar from '@/components/search-bar'
import ScrollNav from '@/components/scroll-nav'
const lato = Lato({ weight: ["100", "300", "400", "700","900"],subsets: ['latin']  })

export const metadata = {
  title: 'QR Menu',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className={lato.className}>
        <section className='flex flex-col items-center justify-center gap-8 realtive bg-white'>
        <Header/>
        <SearchBar></SearchBar>
        <ScrollNav></ScrollNav>
        </section>
        {children}
        </body>
    </html>
  )
}
