import { Lato } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
const lato = Lato({ weight: ["100", "300", "400", "700","900"],subsets: ['latin']  })

export const metadata = {
  title: 'QR Menu',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={lato.className}>
      <Header/>
        {children}
        </body>
    </html>
  )
}
